name = "codefromanywhere_oapis"
main = "main.ts"
compatibility_date = "2024-12-05"
assets = { directory= "./" }

routes = [
  { pattern = "oapis.org", custom_domain = true },
  { pattern = "www.oapis.org", custom_domain = true }
]